@baseUrl = http://localhost:8000

### 1. Salud (Pública)
GET {{baseUrl}}/
Accept: application/json

### 2. Simular Marcaje
POST {{baseUrl}}/api/v1/hikvision/simular-marcaje?id_empleado=101&id_tienda=1
X-API-Key: 12345

### 3. Simular Marcaje Duplicado
POST {{baseUrl}}/api/v1/hikvision/simular-marcaje?id_empleado=101&id_tienda=1
X-API-Key: 12345

### 4. Webhook Hikvision (ISAPI Event Notification)
POST {{baseUrl}}/api/v1/hikvision/webhook
X-API-Key: 12345
Content-Type: application/json

{
  "AccessControllerEvent": {
    "employeeNoString": "202",
    "dateTime": "2026-09-14T10:00:00",
    "ipAddress": "192.168.20.215"
  }
}

### 5. Reporte TXT Respaldo
GET {{baseUrl}}/api/v1/hikvision/reporte-respaldo
X-API-Key: 12345

### 6. Prueba de Seguridad (Debe dar 403 Forbidden)
GET {{baseUrl}}/api/v1/hikvision/reporte-respaldo
X-API-Key: clave_incorrecta